const express = require('express');
const bodyParser = require('body-parser');

//set port
const port = process.env.PORT || 3000;

const app = express();

//serve the content straight from the distribution folder (output after npm run build)
app.use(express.static("dist"));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

app.use((req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader(
    "Access-Control-Allow-Methods",
    "OPTIONS, GET, POST, PUT, PATCH, DELETE"
  );
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
  next();
});

//routes
const collectionRoutes = require("./routes/collection");
const entityRoutes = require("./routes/entity");

//serve out the APIs
app.use("/api/collections", collectionRoutes);
app.use("/api/entities", entityRoutes);

app.listen(port, () => {
    console.log(`Server has started on port ${port}!`);
});

process.on('uncaughtException', err => {
    if (err.name === 'RequestError') {
        //these errors are generated by a third-party package called got: https://github.com/sindresorhus/got#gotrequesterror
        //we will just log to console only to avoid whole application crashes
        console.error('UncaughtException:', err.message)
    }
});